version: '3.7'

networks:
  app_net:

volumes:
  db:

services:
  backend:
    image: backend
    container_name: backend
    restart: always
    networks:
      app_net:
    ports:
      - 5000:5000
    volumes:
      - ./:/home/app

  nginx:
    image: nginx:stable
    container_name: nginx
    networks:
      app_net:
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./production/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./production/certbot/www/:/etc/nginx/acme_challenge/:ro
      - ./production/certbot/certificate/:/etc/nginx/certificate/:ro

  db:
    image: postgres:14.1
    container_name: db
    restart: always
    networks:
      app_net:
    ports:
      - $DB_PORT:5432
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: $DB_PASS
